# Generated by Django 4.2.3 on 2023-08-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Svecha', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ('name',), 'verbose_name': 'Ингредиенты', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('name',), 'verbose_name': 'Составляющие', 'verbose_name_plural': 'Составляющие'},
        ),
    ]
